name: Generate schema inventory

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/schema/dpp.schema.json'
      - 'packages/schema/tools/extract-schema-paths.mjs'

permissions:
  contents: write
  pull-requests: write

jobs:
  inventory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'   # odstraněno cache: 'npm'

      - name: Install tool deps (no-save)
        run: npm install --no-save @apidevtools/json-schema-ref-parser json-schema-traverse

      - name: Generate CSV of schema paths
        run: |
          mkdir -p knowledge/packs/apparel-v1/relevance
          node packages/schema/tools/extract-schema-paths.mjs \
            packages/schema/dpp.schema.json \
            knowledge/packs/apparel-v1/relevance/schema_paths.csv

      - name: Upload artifact (CSV)
        uses: actions/upload-artifact@v4
        with:
          name: schema_paths_csv
          path: knowledge/packs/apparel-v1/relevance/schema_paths.csv

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/schema-inventory
          title: 'chore: update schema paths inventory'
          commit-message: 'chore: generate schema paths inventory'
          add-paths: |
            knowledge/packs/apparel-v1/relevance/schema_paths.csv
